import { createCipheriv, createDecipheriv, randomBytes, pbkdf2Sync, createHash } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir, hostname, platform, arch, cpus } from "os";

const ALGORITHM = "aes-256-gcm";
const KEY_LEN = 32;
const IV_LEN = 16;
const AUTH_TAG_LEN = 16;
const ITERATIONS = 100_000;
const DIGEST = "sha512";

export const CCS_CONFIG_DIR = `${homedir()}/.config/ccs`;

export class EncryptionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "EncryptionError";
  }
}

/**
 * Returns the path to the machine-id file.
 * Does NOT create the file — caller should call ensureMachineIdFile() first.
 */
export function getMachineIdPath(): string {
  return `${CCS_CONFIG_DIR}/machine-id`;
}

const MACHINE_ID_RECOVERY_WARNING = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  CCS MACHINE ID — READ CAREFULLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This machine ID file was generated by CCS (Claude Code Swap)
and is used to derive the encryption key for your stored API tokens.

KEEP THIS FILE SAFE — if lost, all stored tokens become unreadable.

Do NOT share this file. Do NOT copy it to another machine.
Do NOT edit it unless you know what you are doing.

If your machine changes (reinstall, new hardware), run:
  ccs doctor --export-encrypted-backup

to export your profiles before the old machine ID is lost.

File: ${CCS_CONFIG_DIR}/machine-id
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();

/**
 * Creates the machine-id file if it does not exist.
 * Prints a one-time recovery warning to stdout.
 * Safe to call multiple times — idempotent after first creation.
 * Throws if the file cannot be created.
 */
export function ensureMachineIdFile(): void {
  const machineIdPath = getMachineIdPath();

  if (existsSync(machineIdPath)) return; // already exists — no-op

  // Ensure config directory exists
  mkdirSync(CCS_CONFIG_DIR, { recursive: true });

  // Build fingerprint from current machine as seed for new ID
  const seedParts = [hostname(), platform(), arch(), String(cpus().length)];
  if (platform() === "linux") {
    try {
      seedParts.push(readFileSync("/etc/machine-id", "utf8").trim());
    } catch {
      // nothing to add — homedir used below
    }
  }
  seedParts.push(homedir());
  const seed = createHash("sha256").update(seedParts.join("|")).digest("hex");

  // Generate a stable machine ID from the seed
  const machineId = `ccs-${seed}`;

  writeFileSync(machineIdPath, machineId, { mode: 0o600 });
  if (!process.env.CI) {
    process.stdout.write(`${MACHINE_ID_RECOVERY_WARNING}\n\n`);
  }
}

export class Encryption {
  private _machineFingerprint: string | null = null;

  private get machineFingerprint(): string {
    if (this._machineFingerprint) return this._machineFingerprint;

    const machineIdPath = getMachineIdPath();

    if (!existsSync(machineIdPath)) {
      throw new EncryptionError(
        `Machine ID file not found at ${machineIdPath}.\n` +
          "Run `ccs init` or any `ccs` command to generate it.\n" +
          "See above recovery warning for important information.",
      );
    }

    const machineId = readFileSync(machineIdPath, "utf8").trim();
    this._machineFingerprint = machineId;
    return this._machineFingerprint;
  }

  private deriveKey(): Buffer {
    const salt = createHash("sha256").update(this.machineFingerprint).digest();
    return pbkdf2Sync("ccs-encryption-key", salt, ITERATIONS, KEY_LEN, DIGEST);
  }

  async encrypt(plaintext: string): Promise<string> {
    return this.encryptSync(plaintext);
  }

  encryptSync(plaintext: string): string {
    const key = this.deriveKey();
    const iv = randomBytes(IV_LEN);
    const cipher = createCipheriv(ALGORITHM, key, iv);

    const encrypted = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);

    const authTag = cipher.getAuthTag();

    // Format: v1:base64(iv ‖ auth_tag ‖ ciphertext)
    return "v1:" + Buffer.concat([iv, authTag, encrypted]).toString("base64");
  }

  async decrypt(encryptedData: string): Promise<string> {
    return this.decryptSync(encryptedData);
  }

  decryptSync(encryptedData: string): string {
    const key = this.deriveKey();

    // Strip version prefix if present
    let body = encryptedData;
    if (encryptedData.startsWith("v1:")) {
      body = encryptedData.slice(3);
    }

    let buf: Buffer;
    try {
      buf = Buffer.from(body, "base64");
    } catch {
      throw new EncryptionError("Invalid base64 input");
    }

    if (buf.length < IV_LEN + AUTH_TAG_LEN) {
      throw new EncryptionError("Ciphertext too short");
    }

    const iv = buf.subarray(0, IV_LEN);
    const authTag = buf.subarray(IV_LEN, IV_LEN + AUTH_TAG_LEN);
    const ciphertext = buf.subarray(IV_LEN + AUTH_TAG_LEN);

    const decipher = createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);

    try {
      return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
    } catch {
      throw new EncryptionError("Decryption failed: auth tag mismatch or corrupted data");
    }
  }
}

let _instance: Encryption | null = null;

export function getEncryption(): Encryption {
  if (!_instance) _instance = new Encryption();
  return _instance;
}

export function encryptForStorage(plaintext: string): string {
  return getEncryption().encryptSync(plaintext);
}

export function decryptFromStorage(encryptedData: string): string {
  return getEncryption().decryptSync(encryptedData);
}
